modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Code : GPL 3.0, Assets : ARR"

[[mods]]
modId = "abyssaldecor"
version = "${version}"
displayName = "Abyssal Decor"
authors = "StarrySock, ThePlasticPotato"
description = '''
(Mostly) Vanilla style decorative blocks, (mostly) inspired by Victorian and Lovecraftian themes!
'''
#logoFile = ""

[[dependencies.abyssaldecor]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abyssaldecor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abyssaldecor]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"